# Generated by Django 5.0.3 on 2024-04-19 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kesho_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_no", models.IntegerField(blank=True, default=0, null=True)),
                ("amount", models.IntegerField(blank=True, default=0, null=True)),
                ("currency", models.CharField(default="ugx", max_length=10, null=True)),
                (
                    "c_pay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kesho_app.categorystay",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kesho_app.baby",
                    ),
                ),
            ],
        ),
    ]
